### ISSUE TITLE
请教 TM1650 命令地址 0x24 的由来

### ISSUE THREAD

**Issue by Ginurx** [microbit-makecode-packages/TM1650_cn#1]
根据天威电子提供的 [TM1650 资料](http://www.titanmec.com/product/display-drivers/led-panel-display-driver-chip/20220817104.html)，系统命令的地址是 0x48，请教为何驱动中的系统命令地址是 0x24？根据 I2C 扫描的结果的确 0x24 才是有效的。

我是不是理解错了什么东西，请指教。

**Comment by shaoziyang** [comment]
因为 I2C 地址是按照7位方式计算的，资料写的不规范。在 2024年5月25日，11:47，Jeffrey Zhuang ***@***.***> 写道：﻿
根据天威电子提供的 TM1650 资料，系统命令的地址是 0x48，请教为何驱动中的系统命令地址是 0x24？根据 I2C 扫描的结果的确 0x24 才是有效的。
我是不是理解错了什么东西，请指教。

**Comment by Ginurx** [comment]
原来如此，非常感谢！

**Comment by Ginurx** [comment]
题外话，论坛的注册邮件 126 邮箱收不到（垃圾箱也没有）

**Comment by shaoziyang** [comment]
现在阿里服务器有问题，不稳定，等换服务器后会好一些。
注册如果收不到邮件，暂时可以在论坛联系中，发邮件给管理员，提供注册名激活。
> 题外话，论坛的注册邮件 126 邮箱收不到（垃圾箱也没有
